### ISSUE TITLE
Simple if statement 

### ISSUE THREAD

**Issue by Harishankarvb** [Harishankarvb/10_days_coding_challenge#1]
write a python program that takes an input from 0 to 99 and prints weather it is a two digit or one digit number.

**Comment by Devamadhavan** [comment]
num = int(input("Enter a number from 0 to 99"))
if (num<0) or (num>99): 
     print('Invalid input')
else:
     if num<10:
          print('It is a one digit number')
     else:
          print('It is a two digit number')

**Comment by Athul2006588** [comment]
num=int("enter number between 0 and 99")
If num>10:
     Print("the number is two digit")
else:
    Print("the number is one digit")

**Comment by Ayyappa4** [comment]
Num=int(input("enter a number from 0 to 99"))
If number >=10:
      Print("the number is two digit")
else:
      Print("the number is one digit")

**Comment by Dalwin63** [comment]
number = int(input("Enter a number between 0 and 99: "))
if number < 10:
        print("It is a one digit number.")
    else:
        print("It is a two digit number.")
