### ISSUE TITLE
Define function_2

### ISSUE THREAD

**Issue by Harishankarvb** [Harishankarvb/10_days_coding_challenge#10]
Write a python function to convert the length from meter(m) to centimeter(cm) inputted by the user.

(1m = 100cm)

**Comment by Dalwin63** [comment]
def convert_m_to_cm():
    meters = float(input("Enter the length in meters: ")
    centimeters = meters * 100
    print(f"{meters} meters is equal to {centimeters}")

**Comment by Athul2006588** [comment]
def meter_to_centimeter():
meters=float(input("enter the length in meters".  )
Centimeter=meters*100
print (centimeters )

@Athul2006588    Where is the indentation?
                               also try to make the program more informative.

**Comment by Ayyappa4** [comment]
def convert_m_to_cm():
meters = float(input("Enter the length in meters: ")
centimeters = meters * 100
print(f"{meters} meters is equal to {centimeters}")
