### ISSUE TITLE
Elif statement

### ISSUE THREAD

**Issue by Harishankarvb** [Harishankarvb/10_days_coding_challenge#2]
Write a Python program to calculate an employee's bonus based on their years of service. The rules are as follows:

1. If the employee has worked for more than 10 years, they receive a 15% bonus.
2. If the employee has worked for more than 5 years but 10 years or less, they receive a 10% 
    bonus.
3. If the employee has worked for more than 2 years but 5 years or less, they receive a 5% 
    bonus.
4. If the employee has worked for 2 years or less, they receive no bonus.
Take the number of years as input and output the bonus percentage.

**Comment by Ayyappa4** [comment]
years=int(input("enter the years of service")) 
if years of service > 10 years:
     print("they recieve 15% bonus")
 elif years of service > 5 years and <10 years:
       print("they recieve 10% bonus")
 elif years of service > 2 years and < 5 years:
       print("they recieve 5% bonus")
  else:
       print("they recieve no bonus")

**Comment by Athul2006588** [comment]
years=int(input("enter the number of years service"))
If years >10:
       Print("you will receive 15% bonus")
elif 5< years> 10
       Print("you will receive 10% bonus")
elif 2<years>5
      Print("you will receive 5% bonus")
else 
     Print("they receive no bonus")

**Comment by Athul2006588** [comment]
years=int(input("enter the number of years service"))
If years >10:
       Print("you will receive 15% bonus")
elif 5< years> 10
       Print("you will receive 10% bonus")
elif 2<years>5
       Print("you will receive 5% bonus")
else
       Print("they receive no bonus")

**Comment by Devamadhavan** [comment]
years = int(input("Enter the number of years of service"))
if years > 10:
    print ("You will recieve a bonus of 15%")
elif years > 5:
    print ("You will recieve a bonus of 10%")
elif years > 2:
    print ("You will recieve a bonus of 5%")
else:
    print ("You will not recieve any bonus..")
