### ISSUE TITLE
While Loop 

### ISSUE THREAD

**Issue by Harishankarvb** [Harishankarvb/10_days_coding_challenge#4]
Write a python program that prompts the user to repeatedly input some numbers and print their sum. The program ends when the user says no more numbers to input (normal termination) or the program should also abort when the number entered is less than zero.

note : Should include both the ways of termination in the program.

**Comment by Devamadhavan** [comment]
sum = 0
count = 0
while (count == 0):
    num = input("Enter a number or 's' to stop")
    if num == 's' or num == 'S':
        print("Normal termination")
        count = 1
    elif int(num) < 0:
        print("Abort. Number less than zero")
        count = 1
    else:
        sum = sum + int(num)
print("The sum of the numbers is ",sum)

**Comment by Athul2006588** [comment]
num=10+10
while(num<=20):
    print(num)
    num=num+1
    print("no more numbers to input")

**Comment by Ayyappa4** [comment]
total = 0
    while True:
     
 
            user_input = input("Enter a number (or type 'no' to stop): ")
            
           
            if user_input == "no":
                print("Normal termination.")
                break
            
           
            number = float(user_input)
            
           
            if number < 0:
                print("Aborting: Negative number entered.")
                break
            
        
            total += number
            print("total")

**Comment by Ayyappa4** [comment]
total = 0
while true:
 user_input = input("Enter a number (or type 'no' to stop): ").strip().lower()
 if user_input == "no":
 print("Normal termination.")
  break
number = float(user_input)
if number < 0:
 print("Aborting: Negative number entered.")
 break      
total += number
 print("total")
