### ISSUE TITLE
list 

### ISSUE THREAD

**Issue by Harishankarvb** [Harishankarvb/10_days_coding_challenge#5]
Question 1:
Write a python program to multiply all the numbers in a list and display the product.
(   list = [1,5,8,10,30]  ) 

Question 2:
Write a python program to swap the first and last values of a list.
(   list = [3,2,1]   )
hint : using list index

**Comment by Devamadhavan** [comment]
2) l = [3,2,1]
temp = l[0]
l[0] = l[len(l)-1]
l[len(l)-1] = temp
print(l)

**Comment by Devamadhavan** [comment]
1) l=[1,5,8,10,30]
product = 1
for i in l:
    product = product * i
print('The product of numbers in the list is',product)

**Comment by Dalwin63** [comment]
Question 1:
Write a python program to multiply all the numbers in a list and display the product.
( list = [1,5,8,10,30] )


numbers = [1, 5, 8, 10, 30]
product = 1
for i in numbers:
    num=product*i
print("The product of all numbers in the list is:", product)

**Comment by Dalwin63** [comment]
2.

numbers = [3, 2, 1]
temp = l[0]
l[0] = l[len(l)-1]
l[len(l)-1] = temp

print(numbers)
