### ISSUE TITLE
Tuple 

### ISSUE THREAD

**Issue by Harishankarvb** [Harishankarvb/10_days_coding_challenge#6]
Write a python program to input the names of n students and store them in a tuple. Also input a name from the user and find if this student is present in the tuple or not.

Hint: First create a list and convert it to a tuple.

**Comment by Ayyappa4** [comment]
Student_list=([enter the names of students])
  Print ("Alex" in names)

**Comment by Dalwin63** [comment]
students = tuple(input("Enter student name: ") 
int(input("Enter number of students: "))
if input("Enter name to search: ") in students:
    print("Student is present.")
else:
    print("Student is not present.")
