### ISSUE TITLE
Tuple 2 

### ISSUE THREAD

**Issue by Harishankarvb** [Harishankarvb/10_days_coding_challenge#7]
Write a python program to check if a tuple has any duplicate elements or not.

note : you can define your own tuple in the beginning (numbers only).

**Comment by Dalwin63** [comment]
def duplicates():
    num= (1, 2, 3, 4, 5, 6, 3, 7)
    if len(num) != len(set(num)):
        print("The tuple has duplicate elements.")
    else:
        print("The tuple does not have duplicate elements.")

**Comment by Athul2006588** [comment]
def has_duplicate():
numbers=(1,2,2,3,4,5,6,6)
If len(numbers)!=len(set(numbers)):
print("the tuple contains duplicate elements ")
else:
print("the tuple does not contains duplicate elements ")
