### ISSUE TITLE
Set 

### ISSUE THREAD

**Issue by Harishankarvb** [Harishankarvb/10_days_coding_challenge#8]
Write a python program to iterate through a set. 

note: The output should be printed in a single line.

**Comment by Dalwin63** [comment]
def set():
    my_set = {10, 20, 30, 40, 50}
    print(my_set)


@Dalwin63 Where is the loop?
                    I said to loop not define function

**Comment by Athul2006588** [comment]
Set={1,2,3,4,5}
print(set, end=" ")

@Athul2006588    Where is the loop?
                              the question is iterate not just print.
