### ISSUE TITLE
Define Function_1

### ISSUE THREAD

**Issue by Harishankarvb** [Harishankarvb/10_days_coding_challenge#9]
Write a python program to invoking a function to calculate statistical parameters and return sum, average, minimum and maximum values of a set of values.

hint : the values can be given as a list in the function call.

**Comment by Dalwin63** [comment]
def calculate_statistics(values):
    values = [10, 20, 30, 40, 50]
    total_sum, average, minimum, maximum = calculate_statistics(values)
    print(f"Sum: (total_sum))
    print(f"Average: (average))
    print(f"Minimum: (minimum))
    print(f"Maximum: (maximum))

@Dalwin63        Where is the indentation?
                           Where is the calculation part?

**Comment by Athul2006588** [comment]
def calculate_statistics ():
total=sum(values )
avg=total/len(values)
minimum =min(values)
maximum =max(values)
return total, avg, minimum, maximum
